apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-sm
spec:
  provider:
    bitwarden-secrets-manager:
      organizationId: d00e0ecf-235b-4168-8367-b35e00dbf84d # ID que pegamos no bws list
      auth:
        secretRef:
          credentials:
            name: bws-access-token
            key: token
            namespace: default
