apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  selector:
    matchLabels:
      app: nats
  serviceName: "nats"
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
    spec:
      nodeSelector:
        hardware-type: high-performance
      containers:
      - name: nats
        image: nats:2.10-alpine
        args: ["-js", "-sd", "/data"] # Ativando JetStream e definindo diretório de dados
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        volumeMounts:
        - name: nats-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: nats-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitor
    port: 8222
    targetPort: 8222
