apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: postgres-bitwardensecret
spec:
  organizationId: "d00e0ecf-235b-4168-8367-b35e00dbf84d"
  secretName: postgres-credentials # Nome do segredo que o K8s vai criar
  authToken:
    name: bw-auth-token
    key: token
  map:
    - bwSecretId: "70a8c524-eb0a-4445-a727-b3f000567938" # ID do SC_DB_PASSWORD que vimos antes
      secretKeyName: password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        hardware-type: high-performance
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
